# Generated by Django 3.2 on 2021-09-22 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=100)),
                ('telephone_utilisateur', models.CharField(max_length=10)),
                ('mdp_utilisateur', models.CharField(max_length=50)),
                ('statut_utilisateur', models.BooleanField(default=False)),
                ('role', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur_role', to='api.role')),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_voyage', models.CharField(max_length=100)),
                ('frais_voyage', models.BigIntegerField()),
                ('nombre_place', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_voiture', models.CharField(max_length=7)),
                ('etat_voiture', models.BooleanField(default=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voiture_utilisateur', to='api.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.BigIntegerField()),
                ('avance_paye', models.BigIntegerField()),
                ('position_place', models.CharField(max_length=100)),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_destination', models.CharField(max_length=100)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_utilisateur', to='api.utilisateur')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_utilisateur', to='api.voyage')),
            ],
        ),
    ]
