# Generated by Django 3.2 on 2021-10-06 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseVoiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=100)),
                ('arrive', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HoraireClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaireclasse_classevoiture', to='api.classevoiture')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaireclasse_destination', to=settings.AUTH_USER_MODEL)),
                ('horaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaireclasse_horaire', to='api.horaire')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='ville_depart',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='ville_destination',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='reservation',
            name='horaireclasse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_horaireclasse', to='api.horaire'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Voyage',
        ),
        migrations.AddField(
            model_name='voiture',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voiture_classevoiture', to='api.classevoiture'),
            preserve_default=False,
        ),
    ]
