# Generated by Django 3.2 on 2021-10-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='name',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='CIN',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
