# Generated by Django 3.2 on 2021-10-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211006_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire',
            name='heure',
            field=models.CharField(max_length=20),
        ),
    ]
