# Generated by Django 3.2 on 2021-10-05 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_horaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='voyage',
        ),
        migrations.AddField(
            model_name='reservation',
            name='voiture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_voiture', to='api.voiture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voyage',
            name='heure',
            field=models.ManyToManyField(related_name='voyage_horaire', to='api.Horaire'),
        ),
    ]
